apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-service
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: voting-service
          image: peap/voting-service:prod
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
