apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: peap-local

resources:
  - ../../base
  - namespace.yaml

patches:
  - path: identity-deployment-patch.yaml
  - path: product-deployment-patch.yaml
  - path: voting-deployment-patch.yaml
  - path: review-deployment-patch.yaml
  - path: gateway-deployment-patch.yaml
  - path: analytics-deployment-patch.yaml
  - path: secret-patch.yaml
