apiVersion: v1
kind: Secret
metadata:
  name: peap-db-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "local_dev_password"
  JWT_SECRET: "local-dev-secret-change-me-please-0123456789ABCDEF"
