apiVersion: v1
kind: ConfigMap
metadata:
  name: review-service-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/review_db"
  SPRING_DATASOURCE_USERNAME: "appuser"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
