apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
data:
  01-init-databases.sql: |
    CREATE DATABASE product_db OWNER appuser;
    CREATE DATABASE voting_db OWNER appuser;
    CREATE DATABASE review_db OWNER appuser;
