apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    app: voting-service
spec:
  selector:
    app: voting-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
