apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - common
  - postgres
  - redis
  - kafka
  - api-gateway
  - identity-service
  - product-service
  - voting-service
  - review-service
  - analytics-service
  - flink
