apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: identity-service
          image: peap/identity-service:qa
